### ISSUE TITLE
would this help you?

### ISSUE THREAD

**Issue by SimonCropp** [tmccarthy/ausvotes#49]
https://github.com/SimonCropp/AustralianElectorates

specifically the [Map variants](https://github.com/SimonCropp/AustralianElectorates#map-variants) for both [Future](https://github.com/SimonCropp/AustralianElectorates/tree/master/Data/Maps/Future) and [Current](https://github.com/SimonCropp/AustralianElectorates/tree/master/Data/Maps/Current).

There is also [curated](https://github.com/SimonCropp/AustralianElectorates/tree/master/Data/MapsCurated) maps where i have selected a specific from the varies maps so as to have a predictable size for website loading.

if not, feel free to close :)

**Comment by tmccarthy** [comment]
Hi Simon! These are fantastic!

Right at this moment I'm not doing anything that would make use of these, but my hope is to eventually build some sort of map-based portal. When that happens these look perfect.
